return {
  importance = -1,
  npc = "child",
  noShow = true,
  repeatCheck = false,
  dialogue = {
    { "tag", "one" },
    { "freeze", "player" },
    { "setCharacter", "child" },
    "Did you know that sea turtles existed for so long? 200 million years! From the time of the dinosaurs. They lasted much longer!",
    { "setState", "two" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "two" },
    { "freeze", "player" },
    { "setCharacter", "child" },
    "Did you know that there were 7 different species of sea turtles? But leatherbacks were special because they were softshell!",
    { "setState", "three" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "three" },
    { "freeze", "player" },
    { "setCharacter", "child" },
    "Did you know sea turtles were able to stay underwater for hours and hours even when they sleep?",
    { "setState", "four" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "four" },
    { "freeze", "player" },
    { "setCharacter", "child" },
    "Did you know that global heating led to only female turtles hatching from their nests?",
    { "setState", "five" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "five" },
    { "freeze", "player" },
    { "setCharacter", "child" },
    "Did you know that sea turtles used to come to our shores? And they used the Earth's magnetic fields to navigate! Imagine being able to sense the magnetic field! I wonder what that would be like!",
    { "setState", "six" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "six" },
    { "freeze", "player" },
    { "setCharacter", "child" },
    "Did you know that green sea turtles ate algae? Like the stuff they grow in the aquaponics lab?",
    { "setState", "one" },
    { "unfreeze", "player" },
    { "end" },
  }
}