return {
  importance = -1,
  npc = "electrician",
  noShow = true,
  repeatCheck = false,
  dialogue = {
    { "tag", "one" },
    { "freeze", "player" },
    { "setCharacter", "electrician" },
    "I need to rewire the micro-grid for the storm.",
    { "setState", "two" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "two" },
    { "freeze", "player" },
    { "setCharacter", "electrician" },
    "I need to add more electrolytes to the saltwater battery to increase capacity.",
    { "setState", "three" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "three" },
    { "freeze", "player" },
    { "setCharacter", "electrician" },
    "I love a sunny day, we are all charged up.",
    { "setState", "four" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "four" },
    { "freeze", "player" },
    { "setCharacter", "electrician" },
    "Some of our solar glass panels in the greenhouse came loose.",
    { "setState", "five" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "five" },
    { "freeze", "player" },
    { "setCharacter", "electrician" },
    "Time for a smoothie break.",
    { "setState", "one" },
    { "unfreeze", "player" },
    { "end" },
  }
}
