return {
    { "setCharacter", "player" },
"Hey Lyn, welcome to the textile workshop!",
"What can I do for you today?",
"Mending?",
"A new bag, maybe?",
"Or are you here to collect data on our work for the RRE?",
{ "setCharacter", "lyn" },
"I’d love to have a new bag sometime, but unfortunately, I’m not here for that.",
"I don’t know if you have heard the news...",
"apparently the storm hit the plains quite hard",
{ "setCharacter", "player" },
"oh...",
{ "setCharacter", "lyn" },
"They were still recovering from Cyclone Emory",
"the land there just could not take another 300mm of rain.",
{ "setCharacter", "player" },
"They flooded? Oh, that’s horrible, were any lives lost?",
{ "setCharacter", "lyn" },
"Luckily, no, evacuations went well, and the climate task force was there from the start.",
"But there was vast damage to homes and infrastructure.",
"RRE is coordinating a solidarity drive from all the communities in the network.",
{ "setCharacter", "player" },
"What can I do to help?",
{ "setCharacter", "lyn" },
"Clothes, bags, anything like that is good",
"but more targeted support - ",
"things like period pads",
"theses kind of stuff folks might not have with them, can make all the difference on the ground.",
{ "setCharacter", "player" },
"I’m on it!",
{ "setCharacter", "lyn" },
"Thank you so much, from me and the RRE.",

}