return {
  title = "Zyla's Dilemma",
  description = "Help Zyla with her dress!",
  npc = "zyla", -- Who to talk to to activate the dialogue; isn't needed if repeatCheck is active
  unlock = {
    "quest_2",
  },
  repeatCheck = false,
  dialogue = {
    { "freeze", "player" },
    { "setState", "state_intro"},
    { "addItem", { -- starting items
      { name = "Childish Fabric", tags = { "fabric", "silly", "texture.silly_1" }, },
      { name = "Neutral Fabric", tags = { "fabric", "neutral", "texture.neutral_1" }, },
      { name = "Fancy Fabric", tags = { "fabric", "fancy", "texture.fancy_1" }, },
      -- { name = "n", tags = { "fabric", "texture.neutral_2" }, },
      -- { name = "n", tags = { "fabric", "texture.heirloom_1" }, },
      -- { name = "n", tags = { "fabric", "texture.heirloom_2" }, },
      -- { name = "n", tags = { "fabric", "texture.neutral_3" }, },
      -- { name = "n", tags = { "fabric", "texture.neutral_4" }, },
    } },
    { "tag", "state_intro" },
    { "setQuestNPC", "zyla" },
    { "setObjective", "Listen to Zyla's request" },
    { "teleportToDoor", "zyla", "town-workshop", "town" },
    { "useDoor", "zyla", "town-workshop" },
    { "moveX", "zyla", -3 },
    { "setCharacter", "zyla" },
    "Good morning, I am here to see Rosetta. Is she around? I need my dress repaired.",
    { "setCharacter", "player" },
    "Rosetta is not here this morning. I am here to help with all sewing and mending and would love to help!",
    { "setCharacter", "zyla" },
    "Oh, but Rosetta is the one who made this garment for me, I have been wearing it to my council meetings.",
    { "choice", {
      { "and she did a fine job! Please let me have a look.", "option_one" },
      { "I have just the thing for it!", "option_one" }
    } },
    { "tag", "option_one" },
    { "setObjective", "Find fabric to use" },
    { "addItem", {
      {
        name = "Zyla's Dress",
        id = "zyla_dress",
        tags = { "clothing", "dress", "fabric.fancy" },
        issue = { {
          --[[ issue details for minigame... ]]
        } },
      },
    } },
    { "setCharacter", nil },
    "[b][bounce=5]Added Item to Inventory[/bounce][/b][newline][newline][blink=2]Zyla's Dress[/blink]",
    { "unfreeze", "player" },
    { "setState", "patch_time" },
    { "setObjective", "Patch Zyla's Dress" },
    { "highlight", "interact.patch" }, -- todo highlight patch machine
    { "end" },
    { "tag", "patch_time" },
    { "if", "item", "zyla_dress", "hasTag", "patch.silly", "silly_design" }, -- So the patching minigame would add the "patched.<patchType>" tag to the dress
    { "if", "item", "zyla_dress", "hasTag", "patch.neutral", "neutral_design" },
    { "if", "item", "zyla_dress", "hasTag", "patch.fancy", "fancy_design" },
    { "tag", "not_finished" },
    { "setCharacter", "zyla" },
    "Have you finished my dress?",
    { "end" },
    { "tag", "silly_design" },
    { "setCharacter", "zyla" },
    "Rosetta will hear about this!",
    { "goto", "end_option_one" },
    { "tag", "neutral_design" },
    { "setCharacter", "zyla" },
    "This will do, thank you for your service, young man",
    { "goto", "end_option_one" },
    { "tag", "fancy_design" },
    { "setCharacter", "zyla" },
    "Well, this is quite stylish, you know, I do have a few heirloom fabrics just sitting around my place, I think you might be the person to make good use of them. Can't wait to see what you will make.",
    { "addItem",
      { name = "Old Lady's Heirloom fabric 1" },
      { name = "Old Lady's Heirloom fabric 2" },
    },
    { "goto", "end_option_one" },
    { "tag", "end_option_one" },
    { "questFinished" },
    { "end" },
  }
}