return {
  importance = 100,
  title = "Create pads for the RRE",
  description = "Lyn has requested if we could make some pads.",
  npc = "lyn",
  unlock = {
    "ending",
  },
  dialogue = {
    { "moveToDoor", "lyn", "town-workshop" },
    { "moveX", "lyn", -2 },
    { "setState", "start" },
    { "end" },
    { "tag", "start" },
    { "freeze", "player" },
    { "goHome", "player" },
    { "setCharacter", "player" },
    "Hey Lyn, welcome to the textile workshop!",
    "What can I do for you today?",
    "Mending? A new bag, maybe?",
    "Or are you here to collect data on our work for the RRE?",
    { "setCharacter", "lyn" },
    "I'd love to have a new bag sometime, or maybe a few cool patches on this one would be nice. But, unfortunately, I'm not here for that.",
    "I don't know if you have heard the news...",
    "apparently the storm hit the plains quite hard.",
    { "setCharacter", "player" },
    "Oh...",
    { "setCharacter", "lyn" },
    "They were still recovering from Cyclone Emory.",
    "The land there just could not take another 300mm (almost 12 inches) of rain!",
    { "setCharacter", "player" },
    "They flooded? Oh, that's horrible, were any lives lost?",
    { "setCharacter", "lyn" },
    "Luckily, no, evacuations went well, and the climate task force was there from the start.",
    "But there was vast damage to homes and infrastructure.",
    "RRE is coordinating a solidarity drive from all the communities in the network.",
    { "setCharacter", "player" },
    "What can I do to help?",
    { "setCharacter", "lyn" },
    "Clothes, bags, anything like that is good...",
    "but more targeted support - ",
    "things like period pads,",
    "theses kind of stuff folks might not have with them, can make all the difference on the ground.",
    { "setCharacter", "player" },
    "I'm on it!",
    { "setCharacter", "lyn" },
    "Thank you so much, from me and the RRE.",
    { "addItem", {
      {
        name = "Pad template",
        id = "pad",
        tags = { "clothing", "pad", "fabric.neutral", "issue.patch", "patch.pad", "pad", },
      },
    } },
    { "setCharacter", nil },
    "[b][bounce=7]Added Item to Inventory[/bounce][/b][newline][newline]Pad Template",
    { "setState", "pad_time" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "pad_time" },
    { "freeze", "player" },
    { "if", "item", "pad", "hasTag", "patched", "finish_pad" },
    { "setCharacter", "lyn" },
    "Have any pads for me?",
    { "unfreeze", "player" },
    { "end" },
    { "tag", "finish_pad" },
    { "setCharacter", "lyn" },
    "You're a legend for making these! I'll get them on the next train out.",
    "By the way, if you ever need more of this lovely Northern Regen Co-op hemp cloth, find me and I'll put an order in with the RRE.",
    { "goto", "EOF" },
    { "tag", "EOF" },
    { "removeItem", {
      "pad",
    } },
    { "unfreeze", "player" },
    { "moveX", "lyn", 2 },
    { "useDoor", "lyn", "town-workshop"},
    { "goHome", "lyn" },
    { "questFinished" },
    { "end" },
  }
}
