return {
  importance = 100,
  title = "Patch up Sami",
  description = "Sami has fallen off their bike, help patch them up!",
  npc = "sami",
  unlock = {
    "quest_4",
  },
  dialogue = {
    -- Move sami to workshop and wait for interact
    { "moveToDoor", "sami", "town-workshop" }, -- also uses door
    { "moveX", "sami", -2 },
    { "setState", "start" }, -- wait for interaction
    { "end" },
    { "tag", "start" },
    { "freeze", "player" },
    { "goHome", "player" },
    { "setCharacter", "player" },
    "Sami! How you've been man?",
    { "setCharacter", "sami" },
    "So this is where you ended up? You fit right in!",
    { "setCharacter", "player" },
    "Thanks! I actually love it here, how about you, where are you spending your shifts?",
    { "setCharacter", "sami" },
    "I'm at the bicycle workshop.",
    { "setCharacter", "player" },
    "And.. are you into it?",
    { "setCharacter", "sami" },
    "The repair work is fine,",
    "but it's a bit boring after the tenth flat tire, if I'm honest.",
    "My real passion is building my own designs out of the bits and pieces lying around.",
    { "setCharacter", "player" },
    "Oh! Made anything interesting?",
    { "setCharacter", "sami" },
    "Yeah, so this is why I am here, actually... ",
    "So, long story short,",
    "I made a [swing=5]UNICYCLE[/swing]!",
    "Thought it would be a bit of fun, so I started practising,",
    "and yesterday I bombed.",
    "Fell off, tore my pants,",
    "both knees, if you can believe it.",
    { "setCharacter", "player" },
    "Oh my...",
    { "setCharacter", "sami" },
    "Yeah",
    "So I need a repair, and make it [b]sturdy[/b], please.",
    { "setCharacter", "player" },
    "Sure, but why?",
    { "setCharacter", "sami" },
    "In anticipation of the many more falls to come...",
    { "addItem", {
      {
        name = "Sami's Pants",
        id = "sami_pants",
        tags = { "clothing", "pants", "fabric.neutral", "issue.patch", "patch.sami_pants", },
      },
    } },
    { "setCharacter", nil },
    "[b][bounce=7]Added Item to Inventory[/bounce][/b][newline][newline]Sami's Pants",
    { "setState", "patch_time" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "patch_time" },
    { "freeze", "player" },
    { "if", "item", "sami_pants", "hasTag", "patch.silly",    "happy_design" },
    { "if", "item", "sami_pants", "hasTag", "patch.neutral",  "happy_design" },
    { "if", "item", "sami_pants", "hasTag", "patch.fancy",    "fancy_design" },
    { "if", "item", "sami_pants", "hasTag", "patch.heirloom", "fancy_design" },
    { "if", "item", "sami_pants", "hasTag", "patched",        "thanks" },
    { "setCharacter", "sami" },
    "How are those pants coming along?",
    { "unfreeze", "player" },
    { "end" },
    { "tag", "happy_design" },
    { "setCharacter", "sami" },
    "Solid work! These will definitely hold up now. Thanks a bunch!",
    { "goto", "EOF" },
    { "tag", "fancy_design" },
    { "setCharacter", "sami" },
    "Oh dude, look I appreciate your artistry but I can't practice with these pants, they're too fancy. I'd be a afraid to damage them.",
    { "setCharacter", "player" },
    "Sorry about that, I was excited to use this fabric!",
    { "goto", "EOF" },
    { "tag", "thanks" },
    { "setCharacter", "sami" },
    "Thanks for fixing them up man!",
    { "goto", "EOF" },
    { "tag", "EOF" },
    { "removeItem", {
      "sami_pants",
    } },
    { "setCharacter", "sami" },
    "You know our friend Malika? She started working at the aquaponics labs, anyway she showed me something you'd love!",
    "Their latest experiment... It's Algae cloth, 100% grown in the aquaponics tower! I bet I can wrangle a couple of those for you.",
    { "addItem", {
      { name = "Algae cloth dyed", tags = { "fabric", "neutral", "texture.neutral_2" }, },
    } },
    { "setCharacter", nil },
    "[b][bounce=7]Added Item to Inventory[/bounce][/b][newline][newline]Algae cloth: dyed orange",
    { "unfreeze", "player" },
    { "moveX", "sami", 2 },
    { "useDoor", "sami", "town-workshop" },
    { "goHome", "sami" },
    { "questFinished" },
    { "end" },
  }
}
