return {
  importance = -1,
  npc = "sami",
  noShow = true,
  repeatCheck = false,
  dialogue = {
    { "tag", "one" },
    { "freeze", "player" },
    { "setCharacter", "sami" },
    "I should learn how to juggle.",
    { "setState", "two" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "two" },
    { "freeze", "player" },
    { "setCharacter", "sami" },
    "For my next creation what if made an omnibike...? Just need to fabricate a couple of really big wheels.",
    { "setState", "three" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "three" },
    { "freeze", "player" },
    { "setCharacter", "sami" },
    "Malika is experimenting with bioluminescent algae today, we should go check that out!",
    { "setState", "four" },
    { "unfreeze", "player" },
    { "end" },
    { "tag", "four" },
    { "freeze", "player" },
    { "setCharacter", "sami" },
    "What's for dinner? I am starving...",
    { "setState", "one" },
    { "unfreeze", "player" },
    { "end" },
  }
}
