local anim8 = require("libs.anim8")

local filterNearest = function(image)
  image:setFilter("nearest", "nearest")
end

local filterLinear = function(image)
  image:setFilter("linear", "linear")
end

local threeSlices = require("ui.threeSlices")
local slice3Nearest = function(texture, slice1, slice2, direction)
  filterNearest(texture)
  return threeSlices.new(texture, slice1, slice2, direction)
end

local makePixelAnimation = function(image, frameCount, frameWidth, frameHeight, frameTime)
  filterNearest(image)
  local grid = anim8.newGrid(frameWidth, frameHeight, image:getDimensions())
  local animation = anim8.newAnimation(grid('1-'..frameCount, 1), frameTime)
  animation.image = image
  return animation
end

local loopSource = function(source)
  source:setLooping(true)
  return source
end

local voiceVolume = 0.6

return {
-- Audio | sourceType = "static"/"stream"
  -- UI
  { path = "audio/ui/rollover4.ogg", name = "audio.ui.select.1", sourceType = "static", audioType = "ui", key = "audio.ui.select", volume = .5 },
  { path = "audio/ui/rollover5.ogg", name = "audio.ui.select.2", sourceType = "static", audioType = "ui", key = "audio.ui.select", volume = .5 },
  { path = "audio/ui/SFX_UIClick_01.wav", name = "audio.ui.click.1", sourceType = "static", audioType = "ui", key = "audio.ui.click", volume = 0.7 },
  { path = "audio/ui/SFX_UIClick_02.wav", name = "audio.ui.click.2", sourceType = "static", audioType = "ui", key = "audio.ui.click", volume = 0.7 },
  { path = "audio/ui/SFX_UIClick_03.wav", name = "audio.ui.click.3", sourceType = "static", audioType = "ui", key = "audio.ui.click", volume = 0.7 },

  -- SFX
  { path = "audio/sfx/SFX_Sewing_Loop_V2.wav", name = "audio.sfx.sewing", sourceType = "static", audioType = "sfx", volume = 1.0, onLoad = loopSource },
  { path = "audio/sfx/SFX_FootFall_01.wav", name = "audio.sfx.foot.1", sourceType = "static", audioType = "sfx", key = "audio.sfx.foot", volume = .3 },
  { path = "audio/sfx/SFX_FootFall_02.wav", name = "audio.sfx.foot.2", sourceType = "static", audioType = "sfx", key = "audio.sfx.foot", volume = .3 },
  { path = "audio/sfx/SFX_FootFall_03.wav", name = "audio.sfx.foot.3", sourceType = "static", audioType = "sfx", key = "audio.sfx.foot", volume = .3 },
  { path = "audio/sfx/SFX_FootFall_04.wav", name = "audio.sfx.foot.4", sourceType = "static", audioType = "sfx", key = "audio.sfx.foot", volume = .3 },
  { path = "audio/sfx/SFX_FootFall_05.wav", name = "audio.sfx.foot.5", sourceType = "static", audioType = "sfx", key = "audio.sfx.foot", volume = .3 },
  -- Voice
  { path = "audio/sfx/voice/SFX_Voice_01.wav", name = "audio.sfx.voice.1", sourceType = "static", audioType = "sfx", key = "audio.sfx.voice", volume = voiceVolume },
  { path = "audio/sfx/voice/SFX_Voice_02.wav", name = "audio.sfx.voice.2", sourceType = "static", audioType = "sfx", key = "audio.sfx.voice", volume = voiceVolume },
  { path = "audio/sfx/voice/SFX_Voice_03.wav", name = "audio.sfx.voice.3", sourceType = "static", audioType = "sfx", key = "audio.sfx.voice", volume = voiceVolume },
  { path = "audio/sfx/voice/SFX_Voice_04.wav", name = "audio.sfx.voice.4", sourceType = "static", audioType = "sfx", key = "audio.sfx.voice", volume = voiceVolume },
  { path = "audio/sfx/voice/SFX_Voice_05.wav", name = "audio.sfx.voice.5", sourceType = "static", audioType = "sfx", key = "audio.sfx.voice", volume = voiceVolume },
  { path = "audio/sfx/voice/SFX_Voice_06.wav", name = "audio.sfx.voice.6", sourceType = "static", audioType = "sfx", key = "audio.sfx.voice", volume = voiceVolume },
  { path = "audio/sfx/voice/SFX_Voice_07.wav", name = "audio.sfx.voice.7", sourceType = "static", audioType = "sfx", key = "audio.sfx.voice", volume = voiceVolume },

  -- Music
  { path = "audio/music/Solarpunk_Menu_Loop.wav", name = "audio.music.menu", sourceType = "stream", audioType = "music", volume = 1.0, onLoad = loopSource },
  { path = "audio/music/SolarPunk Jam Outside_Loop_V1.wav", name = "audio.music.town", sourceType = "stream", audioType = "music", volume = 1.0, onLoad = loopSource },
  { path = "audio/music/Solarpunk_Workshop_V1.wav", name = "audio.music.workshop", sourceType = "stream", audioType = "music", volume = 1.0, onLoad = loopSource },
  { path = "audio/music/Solarpunk_Mini-Game_V2.wav", name = "audio.music.minigame", sourceType = "stream", audioType = "music", volume = 1.0, onLoad = loopSource },

  -- Fonts
  { path = "fonts/Roboto_Mono/RobotoMono-Light.ttf",            name = "fonts.light" },
  { path = "fonts/Roboto_Mono/RobotoMono-LightItalic.ttf",      name = "fonts.light.italic" },

  { path = "fonts/Roboto_Mono/RobotoMono-Regular.ttf",          name = "fonts.regular" },
  { path = "fonts/Roboto_Mono/RobotoMono-Bold.ttf",             name = "fonts.regular.bold" },
  { path = "fonts/Roboto_Mono/RobotoMono-Italic.ttf",           name = "fonts.regular.italic" },
  { path = "fonts/Roboto_Mono/RobotoMono-BoldItalic.ttf",       name = "fonts.regular.boldItalic" },

  { path = "fonts/Roboto_Mono/RobotoMono-Medium.ttf",           name = "fonts.medium" },
  { path = "fonts/Roboto_Mono/RobotoMono-MediumItalic.ttf",     name = "fonts.medium.italic" },

  { path = "fonts/Abel/Abel-Regular.ttf", name = "fonts.abel" },
-- Fabric
  { path = "fabric/fancy_1.png", name = "fabric.fancy_1", onLoad = filterLinear },
  { path = "fabric/heirloom_1.png", name = "fabric.heirloom_1", onLoad = filterLinear },
  { path = "fabric/heirloom_2.png", name = "fabric.heirloom_2", onLoad = filterLinear },
  { path = "fabric/neutral_1.png", name = "fabric.neutral_1", onLoad = filterLinear },
  { path = "fabric/neutral_2.png", name = "fabric.neutral_2", onLoad = filterLinear },
  { path = "fabric/neutral_3.png", name = "fabric.neutral_3", onLoad = filterLinear },
  { path = "fabric/neutral_4.png", name = "fabric.neutral_4", onLoad = filterLinear },
  { path = "fabric/silly_1.png", name = "fabric.silly_1", onLoad = filterLinear },

-- UI
  { path = "UI/logoES.png", name = "ui.logoES", onLoad = filterNearest },
  { path = "UI/basic_3slice.png", name = "ui.3slice.basic", onLoad = slice3Nearest, 16, 96 },
  { path = "UI/tab_3slice.png", name = "ui.3slice.tab", onLoad = slice3Nearest, 128, 130 },
  { path = "UI/tab2_3slice.png", name = "ui.3slice.tab2", onLoad = slice3Nearest, 8, 56 },
  -- Cursor
  { path = "UI/cursor/navigation_e.png", name = "ui.cursor.navigation.east" },
  { path = "UI/cursor/navigation_w.png", name = "ui.cursor.navigation.west" },
-- Input
  -- Digit
  { path = "UI/input/pc/keyboard_0_outline.png", name = "input.pc.0", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_1_outline.png", name = "input.pc.1", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_2_outline.png", name = "input.pc.2", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_3_outline.png", name = "input.pc.3", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_4_outline.png", name = "input.pc.4", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_5_outline.png", name = "input.pc.5", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_6_outline.png", name = "input.pc.6", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_7_outline.png", name = "input.pc.7", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_8_outline.png", name = "input.pc.8", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_9_outline.png", name = "input.pc.9", onLoad = filterLinear },
  -- Character
  { path = "UI/input/pc/keyboard_a_outline.png", name = "input.pc.a", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_b_outline.png", name = "input.pc.b", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_c_outline.png", name = "input.pc.c", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_d_outline.png", name = "input.pc.d", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_e_outline.png", name = "input.pc.e", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f_outline.png", name = "input.pc.f", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_g_outline.png", name = "input.pc.g", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_h_outline.png", name = "input.pc.h", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_i_outline.png", name = "input.pc.i", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_j_outline.png", name = "input.pc.j", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_k_outline.png", name = "input.pc.k", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_l_outline.png", name = "input.pc.l", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_m_outline.png", name = "input.pc.m", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_n_outline.png", name = "input.pc.n", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_o_outline.png", name = "input.pc.o", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_p_outline.png", name = "input.pc.p", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_q_outline.png", name = "input.pc.q", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_r_outline.png", name = "input.pc.r", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_s_outline.png", name = "input.pc.s", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_t_outline.png", name = "input.pc.t", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_u_outline.png", name = "input.pc.u", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_v_outline.png", name = "input.pc.v", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_w_outline.png", name = "input.pc.w", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_x_outline.png", name = "input.pc.x", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_y_outline.png", name = "input.pc.y", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_z_outline.png", name = "input.pc.z", onLoad = filterLinear },
  -- Arrow
  { path = "UI/input/pc/keyboard_arrow_down_outline.png", name = "input.pc.arrow.down", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrow_left_outline.png", name = "input.pc.arrow.left", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrow_right_outline.png", name = "input.pc.arrow.right", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrow_up_outline.png", name = "input.pc.arrow.up", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrows.png", name = "input.pc.arrows", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrows_all.png", name = "input.pc.arrows.all", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrows_down.png", name = "input.pc.arrows.down", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrows_left.png", name = "input.pc.arrows.left", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrows_right.png", name = "input.pc.arrows.right", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrows_up.png", name = "input.pc.arrows.up", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrows_horizontal.png", name = "input.pc.arrows.horizontal", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_arrows_vertical.png", name = "input.pc.arrows.vertical", onLoad = filterLinear },
  -- Punctuation
  { path = "UI/input/pc/keyboard_alt_outline.png", name = "input.pc.alt", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_any_outline.png", name = "input.pc.any", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_apostrophe_outline.png", name = "input.pc.'", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_asterisk_outline.png", name = "input.pc.*", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_backspace_icon_outline.png", name = "input.pc.backspace", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_bracket_close_outline.png", name = "input.pc.]", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_bracket_greater_outline.png", name = "input.pc.>", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_bracket_less_outline.png", name = "input.pc.<", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_bracket_open_outline.png", name = "input.pc.[", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_capslock_icon_outline.png", name = "input.pc.capslock", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_caret_outline.png", name = "input.pc.^", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_colon_outline.png", name = "input.pc.:", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_comma_outline.png", name = "input.pc.,", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_command_outline.png", name = "input.pc.command", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_ctrl_outline.png", name = "input.pc.ctrl", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_delete_outline.png", name = "input.pc.delete", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_end_outline.png", name = "input.pc.end", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_equals_outline.png", name = "input.pc.=", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_escape_outline.png", name = "input.pc.escape", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_exclamation_outline.png", name = "input.pc.!", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_home_outline.png", name = "input.pc.home", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_insert_outline.png", name = "input.pc.insert", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_minus_outline.png", name = "input.pc.-", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_numlock_outline.png", name = "input.pc.numlock", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_numpad_enter_outline.png", name = "input.pc.kpenter", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_numpad_plus_outline.png", name = "input.pc.kp+", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_option_outline.png", name = "input.pc.option", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_page_down_outline.png", name = "input.pc.pagedown", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_page_up_outline.png", name = "input.pc.pageup", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_period_outline.png", name = "input.pc..", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_plus_outline.png", name = "input.pc.+", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_printscreen_outline.png", name = "input.pc.printscreen", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_question_outline.png", name = "input.pc.?", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_quote_outline.png", name = "input.pc.\"", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_return_outline.png", name = "input.pc.return", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_semicolon_outline.png", name = "input.pc.;", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_shift_icon_outline.png", name = "input.pc.shift", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_slash_back_outline.png", name = "input.pc.\\", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_slash_forward_outline.png", name = "input.pc./", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_space_icon_outline.png", name = "input.pc.space", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_tab_outline.png", name = "input.pc.tab", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_tilde_outline.png", name = "input.pc.~", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_win_outline.png", name = "input.pc.windows", onLoad = filterLinear },
  -- Functional
  { path = "UI/input/pc/keyboard_f1_outline.png", name = "input.pc.f1", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f2_outline.png", name = "input.pc.f2", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f3_outline.png", name = "input.pc.f3", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f4_outline.png", name = "input.pc.f4", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f5_outline.png", name = "input.pc.f5", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f6_outline.png", name = "input.pc.f6", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f7_outline.png", name = "input.pc.f7", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f8_outline.png", name = "input.pc.f8", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f9_outline.png", name = "input.pc.f9", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f10_outline.png", name = "input.pc.f10", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f11_outline.png", name = "input.pc.f11", onLoad = filterLinear },
  { path = "UI/input/pc/keyboard_f12_outline.png", name = "input.pc.f12", onLoad = filterLinear },
  -- Mouse
  { path = "UI/input/pc/mouse.png", name = "input.pc.mouse", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_left.png", name = "input.pc.mouse.left", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_move.png", name = "input.pc.mouse.move", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_right.png", name = "input.pc.mouse.right", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_scroll.png", name = "input.pc.mouse.scroll", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_scroll_down.png", name = "input.pc.mouse.scroll.down", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_scroll_up.png", name = "input.pc.mouse.scroll.up", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_scroll_vertical.png", name = "input.pc.mouse.scroll.vertical", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_small.png", name = "input.pc.mouse.small", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_horizontal.png", name = "input.pc.mouse.horizontal", onLoad = filterLinear },
  { path = "UI/input/pc/mouse_vertical.png", name = "input.pc.mouse.vertical", onLoad = filterLinear },
  -- Gamepad - XBOX
  { path = "UI/input/xbox/controller_xbox360.png", name = "input.xbox.360", onLoad = filterLinear },
  { path = "UI/input/xbox/controller_xboxone.png", name = "input.xbox.one", onLoad = filterLinear },
  { path = "UI/input/xbox/controller_xboxseries.png", name = "input.xbox.series", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_back_icon_outline.png", name = "input.xbox.back", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_color_a_outline.png", name = "input.xbox.a", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_color_b_outline.png", name = "input.xbox.b", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_color_x_outline.png", name = "input.xbox.x", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_color_y_outline.png", name = "input.xbox.y", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_menu_outline.png", name = "input.xbox.menu", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_share_outline.png", name = "input.xbox.share", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_start_icon_outline.png", name = "input.xbox.start", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_button_view_outline.png", name = "input.xbox.view", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_dpad.png", name = "input.xbox.dpad", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_dpad_all.png", name = "input.xbox.dpad.all", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_dpad_down.png", name = "input.xbox.dpad.down", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_dpad_horizontal.png", name = "input.xbox.dpad.horizontal", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_dpad_left.png", name = "input.xbox.dpad.left", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_dpad_right.png", name = "input.xbox.dpad.right", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_dpad_up.png", name = "input.xbox.dpad.up", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_dpad_vertical.png", name = "input.xbox.dpad.vertical", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_guide_outline.png", name = "input.xbox.guide", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_lb_outline.png", name = "input.xbox.leftbutton", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_lt_outline.png", name = "input.xbox.lefttrigger", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_lt.png", name = "input.xbox.lefttrigger.highlight", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_rb_outline.png", name = "input.xbox.rightbutton", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_rt_outline.png", name = "input.xbox.righttrigger", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_rt.png", name = "input.xbox.righttrigger.highlight", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_l.png", name = "input.xbox.leftstick", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_l_down.png", name = "input.xbox.leftstick.down", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_l_horizontal.png", name = "input.xbox.leftstick.horizontal", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_l_left.png", name = "input.xbox.leftstick.left", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_l_press.png", name = "input.xbox.leftstick.press", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_l_right.png", name = "input.xbox.leftstick.right", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_l_up.png", name = "input.xbox.leftstick.up", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_l_vertical.png", name = "input.xbox.leftstick.vertical", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_r.png", name = "input.xbox.rightstick", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_r_down.png", name = "input.xbox.rightstick.down", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_r_horizontal.png", name = "input.xbox.rightstick.horizontal", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_r_left.png", name = "input.xbox.rightstick.left", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_r_press.png", name = "input.xbox.rightstick.press", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_r_right.png", name = "input.xbox.rightstick.right", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_r_up.png", name = "input.xbox.rightstick.up", onLoad = filterLinear },
  { path = "UI/input/xbox/xbox_stick_r_vertical.png", name = "input.xbox.rightstick.vertical", onLoad = filterLinear },
  -- Gamepad - SWITCH
  { path = "UI/input/switch/controller_switch_pro.png", name = "input.switch.pro", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_a_outline.png", name = "input.switch.b", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_b_outline.png", name = "input.switch.a", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_x_outline.png", name = "input.switch.y", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_y_outline.png", name = "input.switch.x", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_home_outline.png", name = "input.switch.home", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_l_outline.png", name = "input.switch.l", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_minus_outline.png", name = "input.switch.minus", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_plus_outline.png", name = "input.switch.plus", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_r_outline.png", name = "input.switch.r", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_sl_outline.png", name = "input.switch.sl", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_sr_outline.png", name = "input.switch.sr", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_zl_outline.png", name = "input.switch.zl", onLoad = filterLinear },
  { path = "UI/input/switch/switch_button_zr_outline.png", name = "input.switch.zr", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons.png", name = "input.switch.buttons", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons_all.png", name = "input.switch.buttons.all", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons_down.png", name = "input.switch.buttons.down", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons_horizontal.png", name = "input.switch.buttons.horizontal", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons_left.png", name = "input.switch.buttons.left", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons_right.png", name = "input.switch.buttons.right", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons_up.png", name = "input.switch.buttons.up", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons_vertical.png", name = "input.switch.buttons.vertical", onLoad = filterLinear },
  { path = "UI/input/switch/switch_buttons_vertical.png", name = "input.switch.buttons.vertical", onLoad = filterLinear },
  { path = "UI/input/switch/switch_dpad.png", name = "input.switch.dpad", onLoad = filterLinear },
  { path = "UI/input/switch/switch_dpad_all.png", name = "input.switch.dpad.all", onLoad = filterLinear },
  { path = "UI/input/switch/switch_dpad_down.png", name = "input.switch.dpad.down", onLoad = filterLinear },
  { path = "UI/input/switch/switch_dpad_horizontal.png", name = "input.switch.dpad.horizontal", onLoad = filterLinear },
  { path = "UI/input/switch/switch_dpad_left.png", name = "input.switch.dpad.left", onLoad = filterLinear },
  { path = "UI/input/switch/switch_dpad_right.png", name = "input.switch.dpad.right", onLoad = filterLinear },
  { path = "UI/input/switch/switch_dpad_up.png", name = "input.switch.dpad.up", onLoad = filterLinear },
  { path = "UI/input/switch/switch_dpad_vertical.png", name = "input.switch.dpad.vertical", onLoad = filterLinear },
  { path = "UI/input/switch/switch_joycon.png", name = "input.switch.joyconpair", onLoad = filterLinear },
  { path = "UI/input/switch/switch_joycon_left.png", name = "input.switch.joyconleft", onLoad = filterLinear },
  { path = "UI/input/switch/switch_joycon_right.png", name = "input.switch.joyconright", onLoad = filterLinear },
  { path = "UI/input/switch/switch_down_outline.png", name = "input.switch.down", onLoad = filterLinear },
  { path = "UI/input/switch/switch_left_outline.png", name = "input.switch.left", onLoad = filterLinear },
  { path = "UI/input/switch/switch_right_outline.png", name = "input.switch.right", onLoad = filterLinear },
  { path = "UI/input/switch/switch_up_outline.png", name = "input.switch.up", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_l.png", name = "input.switch.leftstick", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_l_down.png", name = "input.switch.leftstick.down", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_l_horizontal.png", name = "input.switch.leftstick.horizontal", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_l_left.png", name = "input.switch.leftstick.left", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_l_right.png", name = "input.switch.leftstick.right", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_l_up.png", name = "input.switch.leftstick.up", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_l_vertical.png", name = "input.switch.leftstick.vertical", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_r.png", name = "input.switch.rightstick", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_r_down.png", name = "input.switch.rightstick.down", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_r_horizontal.png", name = "input.switch.rightstick.horizontal", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_r_left.png", name = "input.switch.rightstick.left", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_r_right.png", name = "input.switch.rightstick.right", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_r_up.png", name = "input.switch.rightstick.up", onLoad = filterLinear },
  { path = "UI/input/switch/switch_stick_r_vertical.png", name = "input.switch.rightstick.vertical", onLoad = filterLinear },
  -- Gamepad - PLAYSTATION
  { path = "UI/input/playstation/controller_playstation3.png", name = "input.playstation.ps3", onLoad = filterLinear },
  { path = "UI/input/playstation/controller_playstation4.png", name = "input.playstation.ps4", onLoad = filterLinear },
  { path = "UI/input/playstation/controller_playstation5.png", name = "input.playstation.ps5", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_button_color_circle_outline.png", name = "input.playstation.b", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_button_color_cross_outline.png", name = "input.playstation.a", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_button_color_square_outline.png", name = "input.playstation.x", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_button_color_triangle_outline.png", name = "input.playstation.y", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_dpad.png", name = "input.playstation.dpad", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_dpad_all.png", name = "input.playstation.dpad.all", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_dpad_down.png", name = "input.playstation.dpad.down", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_dpad_horizontal.png", name = "input.playstation.dpad.horizontal", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_dpad_left.png", name = "input.playstation.dpad.left", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_dpad_right.png", name = "input.playstation.dpad.right", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_dpad_up.png", name = "input.playstation.dpad.up", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_dpad_vertical.png", name = "input.playstation.dpad.vertical", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_l.png", name = "input.playstation.leftstick", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_l_down.png", name = "input.playstation.leftstick.down", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_l_horizontal.png", name = "input.playstation.leftstick.horizontal", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_l_left.png", name = "input.playstation.leftstick.left", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_l_right.png", name = "input.playstation.leftstick.right", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_l_up.png", name = "input.playstation.leftstick.up", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_l_vertical.png", name = "input.playstation.leftstick.vertical", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_r.png", name = "input.playstation.rightstick", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_r_down.png", name = "input.playstation.rightstick.down", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_r_horizontal.png", name = "input.playstation.rightstick.horizontal", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_r_left.png", name = "input.playstation.rightstick.left", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_r_right.png", name = "input.playstation.rightstick.right", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_r_up.png", name = "input.playstation.rightstick.up", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_r_vertical.png", name = "input.playstation.rightstick.vertical", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_side_l.png", name = "input.playstation.l3", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_stick_side_r.png", name = "input.playstation.r3", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_trigger_l1_alternative_outline.png", name = "input.playstation.leftbutton", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_trigger_l2_outline.png", name = "input.playstation.lefttrigger", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_trigger_r1_alternative_outline.png", name = "input.playstation.rightbutton", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation_trigger_r2_outline.png", name = "input.playstation.righttrigger", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation3_button_select_outline.png", name = "input.playstation.ps3.select", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation3_button_start_outline.png", name = "input.playstation.ps3.start", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation4_button_options_outline.png", name = "input.playstation.ps4.options", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation4_button_share_outline.png", name = "input.playstation.ps4.share", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation4_touchpad_outline.png", name = "input.playstation.ps4.touchpad", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation4_touchpad_touch_outline.png", name = "input.playstation.ps4.touchpad.touch", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation5_button_create_outline.png", name = "input.playstation.ps5.create", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation5_button_mute_outline.png", name = "input.playstation.ps5.mute", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation5_button_options_outline.png", name = "input.playstation.ps5.options", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation5_touchpad_outline.png", name = "input.playstation.ps5.touchpad", onLoad = filterLinear },
  { path = "UI/input/playstation/playstation5_touchpad_touch_outline.png", name = "input.playstation.ps5.touchpad.touch", onLoad = filterLinear },
  -- Gamepad - STEAM DECK
  { path = "UI/input/steamdeck/controller_steamdeck.png", name = "input.steamdeck", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_a_outline.png", name = "input.steamdeck.a", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_b_outline.png", name = "input.steamdeck.b", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_x_outline.png", name = "input.steamdeck.x", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_y_outline.png", name = "input.steamdeck.y", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_guide_outline.png", name = "input.steamdeck.guide", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_l1_outline.png", name = "input.steamdeck.leftbutton", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_l2_outline.png", name = "input.steamdeck.lefttrigger", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_l4_outline.png", name = "input.steamdeck.paddle.l4", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_l5_outline.png", name = "input.steamdeck.paddle.l5", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_options_outline.png", name = "input.steamdeck.options", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_quickaccess_outline.png", name = "input.steamdeck.quickaccess", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_r1_outline.png", name = "input.steamdeck.rightbutton", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_r2_outline.png", name = "input.steamdeck.righttrigger", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_r4_outline.png", name = "input.steamdeck.paddle.r4", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_r5_outline.png", name = "input.steamdeck.paddle.r5", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_button_view_outline.png", name = "input.steamdeck.view", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_dpad.png", name = "input.steamdeck.dpad", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_dpad_all.png", name = "input.steamdeck.dpad.all", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_dpad_down.png", name = "input.steamdeck.dpad.down", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_dpad_horizontal.png", name = "input.steamdeck.dpad.horizontal", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_dpad_left.png", name = "input.steamdeck.dpad.left", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_dpad_right.png", name = "input.steamdeck.dpad.right", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_dpad_up.png", name = "input.steamdeck.dpad.up", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_dpad_vertical.png", name = "input.steamdeck.dpad.vertical", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l.png", name = "input.steamdeck.leftstick", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_down.png", name = "input.steamdeck.leftstick.down", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_horizontal.png", name = "input.steamdeck.leftstick.horizontal", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_left.png", name = "input.steamdeck.leftstick.left", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_right.png", name = "input.steamdeck.leftstick.right", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_up.png", name = "input.steamdeck.leftstick.up", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_vertical.png", name = "input.steamdeck.leftstick.vertical", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l.png", name = "input.steamdeck.rightstick", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_down.png", name = "input.steamdeck.rightstick.down", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_horizontal.png", name = "input.steamdeck.rightstick.horizontal", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_left.png", name = "input.steamdeck.rightstick.left", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_right.png", name = "input.steamdeck.rightstick.right", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_up.png", name = "input.steamdeck.rightstick.up", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_l_vertical.png", name = "input.steamdeck.rightstick.vertical", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_side_l.png", name = "input.steamdeck.l3", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_stick_side_r.png", name = "input.steamdeck.r3", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_l_outline.png", name = "input.steamdeck.trackpad.left", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_l_all_outline.png", name = "input.steamdeck.trackpad.left.all", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_l_down_outline.png", name = "input.steamdeck.trackpad.left.down", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_l_horizontal_outline.png", name = "input.steamdeck.trackpad.left.horizontal", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_l_left_outline.png", name = "input.steamdeck.trackpad.left.left", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_l_right_outline.png", name = "input.steamdeck.trackpad.left.right", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_l_up_outline.png", name = "input.steamdeck.trackpad.left.up", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_l_vertical_outline.png", name = "input.steamdeck.trackpad.left.vertical", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_r_outline.png", name = "input.steamdeck.trackpad.right", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_r_all_outline.png", name = "input.steamdeck.trackpad.right.all", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_r_down_outline.png", name = "input.steamdeck.trackpad.right.down", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_r_horizontal_outline.png", name = "input.steamdeck.trackpad.right.horizontal", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_r_left_outline.png", name = "input.steamdeck.trackpad.right.left", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_r_right_outline.png", name = "input.steamdeck.trackpad.right.right", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_r_up_outline.png", name = "input.steamdeck.trackpad.right.up", onLoad = filterLinear },
  { path = "UI/input/steamdeck/steamdeck_trackpad_r_vertical_outline.png", name = "input.steamdeck.trackpad.right.vertical", onLoad = filterLinear },
}